apiVersion: v1
kind: ReplicationController
metadata:
  name: database
  labels:
    name: database
spec:
  replicas: 1
  selector:
    name: database
  template:
    metadata:
      labels:
        name: database
    spec:
      containers:
        - name: postgres
          image: postgres:9.5
          env:
            - name: POSTGRES_DB
              value: coolring
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data-disk
      volumes:
        - name: pg-data-disk
          persistentVolumeClaim:
            claimName: pg-data-claim